# Generated by Django 2.1.4 on 2019-01-11 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Sobre Nós', max_length=30, verbose_name='Categoria')),
                ('image', models.ImageField(null=True, upload_to='aboutUs/', verbose_name='Imagem do Sobre nós')),
                ('description', models.TextField(max_length=700, verbose_name='Sobre nós')),
            ],
            options={
                'verbose_name': 'Sobre Nó',
            },
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Depoimento', max_length=50, verbose_name='Categoria')),
                ('autor', models.CharField(default='', max_length=50, verbose_name='Autor')),
                ('conteudo', models.TextField(default='', max_length=500, verbose_name='Conteúdo')),
                ('image', models.ImageField(null=True, upload_to='depoimentos/', verbose_name='Foto Autor')),
            ],
            options={
                'verbose_name': 'Depoimento',
            },
        ),
        migrations.CreateModel(
            name='MVV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='MVV', max_length=50, verbose_name='Categoria')),
                ('mission', models.TextField(default='', max_length=500, verbose_name='Missão')),
                ('vision', models.TextField(default='', max_length=500, verbose_name='Visão')),
                ('values', models.TextField(default='', max_length=500, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'MVV',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Serviço', max_length=50, verbose_name='Categoria')),
                ('titulo', models.CharField(default='', max_length=50, verbose_name='Título')),
                ('conteudo', models.TextField(default='', max_length=500, verbose_name='Conteúdo')),
                ('image', models.ImageField(null=True, upload_to='servicos/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Serviço',
            },
        ),
    ]
