# Generated by Django 2.1.4 on 2018-12-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sobre Nós', max_length=30, verbose_name='Categoria')),
                ('image', models.ImageField(null=True, upload_to='aboutUs/', verbose_name='Imagem do Sobre nós')),
                ('aboutUs', models.TextField(max_length=1000, verbose_name='Sobre nós')),
            ],
            options={
                'verbose_name': 'Sobre Nós',
            },
        ),
        migrations.CreateModel(
            name='MVV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='MVV', max_length=50, verbose_name='Categoria')),
                ('mission', models.TextField(default='', max_length=500, verbose_name='Missão')),
                ('vision', models.TextField(default='', max_length=500, verbose_name='Visão')),
                ('value', models.TextField(default='', max_length=500, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'MVV',
            },
        ),
    ]
