# Generated by Django 2.1.4 on 2018-12-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Sobre Nó'},
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='mvv',
            old_name='categoria',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='mvv',
            old_name='value',
            new_name='values',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='aboutUs',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description',
            field=models.TextField(default='oi', max_length=700, verbose_name='Sobre nós'),
            preserve_default=False,
        ),
    ]
