# Generated by Django 2.1.4 on 2018-12-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Sobre Nó'},
        ),
    ]
