# Generated by Django 2.1.4 on 2019-01-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=50, verbose_name='Nome da pessoa')),
                ('image', models.ImageField(null=True, upload_to='depoiments/', verbose_name='Imagem da pessoa')),
                ('description', models.TextField(max_length=500, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Depoimento',
            },
        ),
        migrations.DeleteModel(
            name='Depoimento',
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Sobre Nós', 'verbose_name_plural': 'Sobre Nós'},
        ),
        migrations.AlterModelOptions(
            name='mvv',
            options={'verbose_name': 'MVV', 'verbose_name_plural': 'MVV'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mvv',
            name='category',
        ),
    ]
