# Generated by Django 2.1.4 on 2019-01-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181217_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Sobre Nós', 'verbose_name_plural': 'Sobre Nós'},
        ),
        migrations.AlterModelOptions(
            name='mvv',
            options={'verbose_name': 'Descrição'},
        ),
        migrations.RemoveField(
            model_name='mvv',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mvv',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='mvv',
            name='values',
        ),
        migrations.RemoveField(
            model_name='mvv',
            name='vision',
        ),
        migrations.AddField(
            model_name='mvv',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='Nome da pessoa'),
        ),
        migrations.AddField(
            model_name='mvv',
            name='description',
            field=models.TextField(default=1, max_length=500, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mvv',
            name='image',
            field=models.ImageField(null=True, upload_to='depoiments/', verbose_name='Imagem da pessoa'),
        ),
    ]
