# Generated by Django 2.1.4 on 2018-12-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181217_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField(default='', max_length=500, verbose_name='Missão')),
                ('autor', models.TextField(default='', max_length=50, verbose_name='Visão')),
                ('image', models.ImageField(null=True, upload_to='core/static/imagens/depoimentos', verbose_name='Foto Autor')),
            ],
            options={
                'verbose_name': 'Depoimento',
            },
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(null=True, upload_to='core/static/imagens/aboutUs/', verbose_name='Imagem do Sobre nós'),
        ),
    ]
