# Generated by Django 2.1.4 on 2018-12-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181216_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='aboutUs',
            field=models.TextField(max_length=700, verbose_name='Sobre nós'),
        ),
    ]
