# Generated by Django 2.1.4 on 2019-01-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190111_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Título')),
                ('content', models.TextField(default='', max_length=500, verbose_name='Conteúdo')),
                ('image', models.ImageField(null=True, upload_to='servicos/', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Serviço',
            },
        ),
    ]
