# Generated by Django 2.1.4 on 2018-12-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181218_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimento',
            name='category',
            field=models.CharField(default='Depoimento', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='autor',
            field=models.TextField(default='', max_length=50, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='conteudo',
            field=models.TextField(default='', max_length=500, verbose_name='Conteúdo'),
        ),
    ]
