# Generated by Django 2.1.4 on 2019-01-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.TextField(default='', max_length=350, verbose_name='Conteúdo'),
        ),
    ]
