# Generated by Django 2.1.4 on 2019-01-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190110_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=50, verbose_name='Nome da pessoa')),
                ('image', models.ImageField(null=True, upload_to='depoiments/', verbose_name='Imagem da pessoa')),
                ('description', models.TextField(max_length=500, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Descrição',
            },
        ),
        migrations.AlterModelOptions(
            name='mvv',
            options={'verbose_name': 'MVV', 'verbose_name_plural': 'MVV'},
        ),
        migrations.RemoveField(
            model_name='mvv',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mvv',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mvv',
            name='image',
        ),
        migrations.AddField(
            model_name='mvv',
            name='category',
            field=models.CharField(default='MVV', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='mvv',
            name='mission',
            field=models.TextField(default='', max_length=500, verbose_name='Missão'),
        ),
        migrations.AddField(
            model_name='mvv',
            name='values',
            field=models.TextField(default='', max_length=500, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='mvv',
            name='vision',
            field=models.TextField(default='', max_length=500, verbose_name='Visão'),
        ),
    ]
