# Generated by Django 2.1.4 on 2018-12-16 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181216_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='mvv',
            old_name='categoria',
            new_name='category',
        ),
    ]
