# Generated by Django 2.1.4 on 2019-01-10 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190110_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depoiments',
            options={'verbose_name': 'Depoimento'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mvv',
            name='category',
        ),
    ]
