# Generated by Django 2.1.4 on 2018-12-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181216_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='aboutUs',
            new_name='description',
        ),
    ]
