# Generated by Django 2.1.4 on 2018-12-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181218_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Serviço', max_length=50, verbose_name='Categoria')),
                ('titulo', models.CharField(default='', max_length=50, verbose_name='Autor')),
                ('conteudo', models.TextField(default='', max_length=500, verbose_name='Conteúdo')),
                ('image', models.ImageField(null=True, upload_to='servicos/', verbose_name='Foto Autor')),
            ],
            options={
                'verbose_name': 'Serviço',
            },
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='autor',
            field=models.CharField(default='', max_length=50, verbose_name='Autor'),
        ),
    ]
