# Generated by Django 2.1.4 on 2019-01-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190110_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoiments',
            name='footer',
            field=models.TextField(default='skds', max_length=100, verbose_name='Rodapé'),
            preserve_default=False,
        ),
    ]
