# Generated by Django 2.1.4 on 2018-12-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181217_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mvv',
            old_name='value',
            new_name='values',
        ),
    ]
