# Generated by Django 2.1.4 on 2018-12-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181218_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='image',
            field=models.ImageField(null=True, upload_to='servicos/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='titulo',
            field=models.CharField(default='', max_length=50, verbose_name='Título'),
        ),
    ]
