# Generated by Django 2.1.4 on 2019-01-10 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_depoiments_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depoiments',
            name='footer',
        ),
    ]
