# Generated by Django 2.1.5 on 2019-01-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_depoiments_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Título do Serviço')),
                ('image', models.ImageField(null=True, upload_to='servicos/', verbose_name='Imagem do Serviço')),
                ('description', models.TextField(max_length=500, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Servico',
            },
        ),
    ]
